[workspace]
resolver = "3"
members = [
    "crates/amcli-xml",
    "crates/amcli-model",
    "crates/amcli-graph",
    "crates/amcli-validate",
    "crates/amcli-view",
    "crates/amcli-render",
    "crates/amcli-cli",
    "xtask",
]

[workspace.package]
version = "0.13.0"
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/arslan-gg/amcli"
rust-version = "1.90"

[workspace.dependencies]
amcli-xml = { path = "crates/amcli-xml" }
amcli-model = { path = "crates/amcli-model" }
amcli-graph = { path = "crates/amcli-graph" }
amcli-validate = { path = "crates/amcli-validate" }
amcli-view = { path = "crates/amcli-view" }
amcli-render = { path = "crates/amcli-render" }

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
