//! Exports.
//!
//! These are conveniences, not interchange formats. Mermaid and DOT both
//! re-lay-out, so they throw away the geometry the model actually stores —
//! useful for a quick picture in a chat window, wrong for anything that has to
//! match the diagram someone drew. `amcli view render` is the faithful path.

use std::collections::HashMap;

use amcli_graph::Graph;
use amcli_model::{ConceptKind, FolderType, Model, ViewId};

use crate::output::{CliError, Code, Output, Row};

pub fn run(g: &Graph<'_>, format: &str, out_path: Option<&str>) -> Result<Output, CliError> {
    let m = g.model();
    let body = match format {
        "csv" => csv(m),
        "mermaid" => mermaid(m),
        "dot" => dot(m),
        "json" => json(g),
        "views" => views(m),
        other => {
            return Err(CliError::new(
                Code::Unsupported,
                "unsupported",
                format!("`{other}` is not an export format"),
            )
            .hint(
                "csv, json, mermaid, dot or views; for a faithful picture use `amcli view render`",
            ));
        }
    };

    match out_path {
        Some(p) => {
            std::fs::write(p, &body)
                .map_err(|e| CliError::new(Code::Io, "io", format!("`{p}`: {e}")))?;
            Ok(Output::one(Row::new().s("path", p.to_string()).n("bytes", body.len() as i64)))
        }
        None => {
            print!("{body}");
            Ok(Output::empty())
        }
    }
}

/// Every view as the batch that would rebuild it, which `amcli apply` accepts.
///
/// A view has no declarative form of its own: what it holds is only visible in
/// the file as geometry, so "which fifteen elements are on C1, and why those"
/// is not a question a diff can answer. Keeping the member lists beside the
/// model answers it but invents a second source of truth that goes stale. This
/// derives the lists from the model instead — read it, review it, edit it,
/// apply it, and the round trip is byte-identical because the ops are the ones
/// that built the views in the first place.
///
/// Only what `view.add` can put back is emitted. Notes, groups, nested objects
/// and references to other views are counted in a comment rather than silently
/// dropped, because a spec that looks complete and is not is worse than none.
///
/// What a view says about itself travels too: the viewpoint on `view.create`
/// and the documentation as a `view.doc` line — an export without the latter
/// applied through `replace` deleted every view's documentation and called
/// the result byte-identical. Properties need no line, because a replace
/// keeps them.
fn views(m: &Model) -> String {
    // A name is the readable target, but only when it belongs to one concept;
    // otherwise the id, which is always right and occasionally unreadable.
    let mut by_name: HashMap<&str, usize> = HashMap::new();
    for c in m.concepts() {
        *by_name.entry(c.name.as_str()).or_default() += 1;
    }

    let mut s = String::from(
        "# Every view, as the batch that rebuilds it. Apply with `amcli apply`.\n\
         # Generated by `amcli export views` — derived from the model, never edited in place.\n",
    );

    // Document order, not the order views happen to sit in the model's slot
    // table: a view deleted and recreated keeps its slot but moves in the file,
    // so slot order stops matching what the file says after the first rebuild —
    // and then the batch reorders the views it was supposed to reproduce.
    let mut folders: Vec<String> = Vec::new();
    let mut ordered: Vec<(ViewId, String)> = Vec::new();
    if let Some(root) = m.top_folder(FolderType::Diagrams) {
        walk_views(m, m.folder(root).node, &mut folders, &mut ordered);
    }

    // Folders first: a view.create naming a folder that does not exist yet
    // fails, and folder.add is idempotent, so declaring them costs nothing.
    for path in &folders {
        let name = path.rsplit('/').next().unwrap_or_default();
        let parent = &path[..path.len() - name.len() - 1];
        s.push_str(&format!(
            "{{\"op\":\"folder.add\",\"parent\":{},\"name\":{}}}\n",
            json_str(parent),
            json_str(name)
        ));
    }

    for (id, folder) in ordered {
        let v = m.view(id);
        s.push('\n');
        s.push_str(&format!("# {}\n", v.name));

        let mut create = format!("{{\"op\":\"view.create\",\"name\":{}", json_str(&v.name));
        if !v.viewpoint.is_empty() {
            create.push_str(&format!(",\"viewpoint\":{}", json_str(&v.viewpoint)));
        }
        if folder != "/Views" {
            create.push_str(&format!(",\"folder\":{}", json_str(&folder)));
        }
        create.push_str(",\"replace\":true}");
        s.push_str(&create);
        s.push('\n');
        if let Some(doc) = m.documentation(v.node).filter(|d| !d.is_empty()) {
            s.push_str(&format!(
                "{{\"op\":\"view.doc\",\"view\":{},\"text\":{}}}\n",
                json_str(&v.name),
                json_str(&doc)
            ));
        }

        let mut skipped = 0;
        for (_, concept) in m.view_objects(id) {
            let Some(concept_id) = concept else {
                skipped += 1;
                continue;
            };
            let Some(c) = m.concept_by_id(&concept_id).map(|i| m.concept(i)) else {
                skipped += 1;
                continue;
            };
            let target = if by_name.get(c.name.as_str()) == Some(&1) {
                c.name.clone()
            } else {
                format!("id:{}", c.id)
            };
            s.push_str(&format!(
                "{{\"op\":\"view.add\",\"view\":{},\"target\":{}}}\n",
                json_str(&v.name),
                json_str(&target)
            ));
        }
        s.push_str(&format!(
            "{{\"op\":\"view.layout\",\"view\":{},\"relayout_all\":true}}\n",
            json_str(&v.name)
        ));
        if skipped > 0 {
            s.push_str(&format!(
                "# {skipped} object(s) on this view are not ArchiMate elements (note, group, \
                 nested object or a reference to another view) and are not rebuilt by this batch\n"
            ));
        }
    }
    s
}

/// Views and their folders in the order the file lists them, depth first.
fn walk_views(
    m: &Model,
    node: amcli_xml::NodeId,
    folders: &mut Vec<String>,
    out: &mut Vec<(ViewId, String)>,
) {
    let here = m
        .doc
        .attr(node, "id")
        .and_then(|id| m.folder_id_by_id(&id))
        .map(|f| m.folder(f).path.clone())
        .unwrap_or_default();
    if here != "/Views" && !here.is_empty() && !folders.contains(&here) {
        folders.push(here.clone());
    }
    for child in m.doc.children(node).collect::<Vec<_>>() {
        match m.doc.local_name(child) {
            "folder" => walk_views(m, child, folders, out),
            "element" => {
                if let Some(v) = m.doc.attr(child, "id").and_then(|id| m.view_by_id(&id)) {
                    out.push((v, here.clone()));
                }
            }
            _ => {}
        }
    }
}

/// A JSON string literal. `serde_json` would do it, but for one field at a
/// time a two-escape helper is less machinery than building a value tree.
fn json_str(v: &str) -> String {
    let mut s = String::with_capacity(v.len() + 2);
    s.push('"');
    for ch in v.chars() {
        match ch {
            '"' => s.push_str("\\\""),
            '\\' => s.push_str("\\\\"),
            '\n' => s.push_str("\\n"),
            '\t' => s.push_str("\\t"),
            c if (c as u32) < 0x20 => s.push_str(&format!("\\u{:04x}", c as u32)),
            c => s.push(c),
        }
    }
    s.push('"');
    s
}

fn csv(m: &Model) -> String {
    let mut s = String::from("id,type,name,layer,folder,source,target,documentation\n");
    for c in m.concepts() {
        let cells = [
            c.id.clone(),
            c.kind.name().to_string(),
            c.name.clone(),
            c.kind.layer().map(|l| l.as_str().to_string()).unwrap_or_default(),
            m.folder_path_of(c).to_string(),
            c.source.clone().unwrap_or_default(),
            c.target.clone().unwrap_or_default(),
            m.documentation(c.node).unwrap_or_default(),
        ];
        s.push_str(&cells.iter().map(|v| quote_csv(v)).collect::<Vec<_>>().join(","));
        s.push('\n');
    }
    s
}

fn quote_csv(v: &str) -> String {
    if v.contains([',', '"', '\n']) {
        format!("\"{}\"", v.replace('"', "\"\""))
    } else {
        v.to_string()
    }
}

/// Mermaid's arrow vocabulary is much smaller than ArchiMate's, so several
/// relationship types necessarily render the same. The collision is documented
/// in the header rather than hidden.
fn mermaid(m: &Model) -> String {
    use amcli_model::RelType::*;
    let mut s = String::from(
        "%% Generated by amcli. Mermaid re-lays-out, so this is not the diagram\n\
         %% anyone drew; use `amcli view render` for that. Mermaid has fewer arrow\n\
         %% styles than ArchiMate, so Composition/Aggregation and\n\
         %% Serving/Triggering each collapse to one glyph.\n\
         flowchart TD\n",
    );
    let mut names: HashMap<&str, String> = HashMap::new();
    for c in m.concepts() {
        if c.kind.is_relationship() {
            continue;
        }
        let key = sanitize(&c.id);
        names.insert(c.id.as_str(), key.clone());
        let label = c.name.replace(['"', '[', ']', '(', ')', '{', '}', '<', '>', ';', '#'], " ");
        // Behaviour elements get the rounded shape, matching the notation.
        let rounded = matches!(&c.kind, ConceptKind::Element(e)
            if amcli_view::notation::figure_of(*e) == amcli_view::Figure::RoundedRect);
        let (open, close) = if rounded { ("(\"", "\")") } else { ("[\"", "\"]") };
        s.push_str(&format!("  {key}{open}{label}{close}\n"));
    }
    for c in m.concepts() {
        let ConceptKind::Relationship(r) = &c.kind else { continue };
        let (Some(src), Some(tgt)) = (c.source.as_deref(), c.target.as_deref()) else { continue };
        let (Some(a), Some(b)) = (names.get(src), names.get(tgt)) else { continue };
        let arrow = match r {
            Composition | Aggregation => "---",
            Realization | Specialization => "-.->",
            Access | Influence => "-.->",
            Association => "---",
            _ => "-->",
        };
        s.push_str(&format!("  {a} {arrow}|{}| {b}\n", r.info().short));
    }
    s
}

fn dot(m: &Model) -> String {
    use amcli_model::RelType::*;
    let mut s = String::from(
        "// Generated by amcli. Graphviz re-lays-out; `amcli view render` keeps\n\
         // the geometry the model stores.\ndigraph model {\n  rankdir=TB;\n  node [shape=box];\n",
    );
    for c in m.concepts() {
        if c.kind.is_relationship() {
            continue;
        }
        s.push_str(&format!("  \"{}\" [label=\"{}\"];\n", c.id, c.name.replace('"', "'")));
    }
    for c in m.concepts() {
        let ConceptKind::Relationship(r) = &c.kind else { continue };
        let (Some(src), Some(tgt)) = (c.source.as_deref(), c.target.as_deref()) else { continue };
        let style = match r {
            Composition => "arrowtail=diamond, dir=back",
            Aggregation => "arrowtail=odiamond, dir=back",
            Realization => "style=dashed, arrowhead=onormal",
            Specialization => "arrowhead=onormal",
            Serving => "arrowhead=vee",
            Access => "style=dotted, arrowhead=vee",
            Influence => "style=dashed, arrowhead=vee",
            Flow => "style=dashed",
            Association => "arrowhead=none",
            _ => "",
        };
        s.push_str(&format!("  \"{src}\" -> \"{tgt}\" [label=\"{}\", {style}];\n", r.info().short));
    }
    s.push_str("}\n");
    s
}

fn json(g: &Graph<'_>) -> String {
    let m = g.model();
    let mut s = String::from("{\n  \"concepts\": [\n");
    let mut first = true;
    for (id, c) in m.concepts_with_ids() {
        if !first {
            s.push_str(",\n");
        }
        first = false;
        let (i, o) = g.degree(id);
        s.push_str(&format!(
            "    {{\"id\":{},\"type\":{},\"name\":{},\"folder\":{},\"in\":{i},\"out\":{o}{}}}",
            crate::output::quote(&c.id),
            crate::output::quote(c.kind.name()),
            crate::output::quote(&c.name),
            crate::output::quote(m.folder_path_of(c)),
            match (&c.source, &c.target) {
                (Some(a), Some(b)) => format!(
                    ",\"source\":{},\"target\":{}",
                    crate::output::quote(a),
                    crate::output::quote(b)
                ),
                _ => String::new(),
            }
        ));
    }
    s.push_str("\n  ]\n}\n");
    s
}

fn sanitize(id: &str) -> String {
    let mut out: String =
        id.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect();
    // A leading digit is not a legal Mermaid node id.
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, 'n');
    }
    out
}
